name: tud-box

services:
  mailhog:
    image: mailhog/mailhog
    container_name: tud-box-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - tud-box_mailhog_data:/var/lib/mailhog

volumes:
  tud-box_mailhog_data: